site_name: Andrew Rushton | Projects
site_url: https://arushton96.github.io/
repo_url: https://github.com/arushton96/arushton96.github.io
edit_uri: edit/main/docs/

nav:
  - Industrial Battery Sorting System:
      - Industrial Battery Sorting System: Industrial-Battery-Sorting-System/index.md
      - Overview: Industrial-Battery-Sorting-System/1-Overview.md
      - System Architecture: Industrial-Battery-Sorting-System/2-System-Architecture.md
      - PLC Control Logic: Industrial-Battery-Sorting-System/3-PLC-Control-Logic.md
      - SCADA & Ignition: Industrial-Battery-Sorting-System/4-SCADA-&-Ignition.md
      - Vision System: Industrial-Battery-Sorting-System/5-Vision-System.md
      - Pneumatic Handling System: Industrial-Battery-Sorting-System/6-Pneumatics.md
      - Challenges & Engineering Decisions: Industrial-Battery-Sorting-System/7-Challenges-&-Engineering-Decisions.md
      - Gallery & Demonstrations: Industrial-Battery-Sorting-System/8-Gallery-&-Demo.md
      - Technical Resources: Industrial-Battery-Sorting-System/9-Technical-Resources.md

  - Embedded Systems Project:
      - Embedded Systems Project: Embedded-Systems_Project/index.md
      - Block Diagram: Embedded-Systems_Project/Block-Diagram.md
      - Component Selection: Embedded-Systems_Project/2-Component-Selection.md
      - ESP32 Table: Embedded-Systems_Project/3-esp-32-table.md
      - BoM: Embedded-Systems_Project/4-Bill-Of-Materials.md
      - API: Embedded-Systems_Project/5-API.md
      - Schematic: Embedded-Systems_Project/6-Schematic-Diagram.md
      - Reflections: Embedded-Systems_Project/7-Reflections.md
      - Resources: Embedded-Systems_Project/8-Resources.md

theme:
  name: material
  custom_dir: custom_theme/
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
  font:
    text: Roboto
  #logo: static/logo.svg
  #favicon: static/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 2

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static/node_modules
  
copyright: "Copyright &copy; 2024 team-name-here"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2023_fall
      name: 2023 Site    
